# Generated by Django 5.2.7 on 2025-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("Programming", "Programming"),
                    ("Design", "Design"),
                    ("Marketing", "Marketing"),
                    ("Business", "Business"),
                ],
                default="Programming",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(help_text="Duration in hours"),
        ),
        migrations.AlterField(
            model_name="course",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
