# Generated by Django 5.2.7 on 2025-10-04 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_category_alter_course_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="price_inr",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
